# Generated by Django 3.2 on 2023-04-18 21:06

# Third Party Library
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "surname",
                    models.CharField(max_length=200, verbose_name="Фамилия"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_image/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "search_job_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Какую работу ищу",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "distant_work",
                    models.BooleanField(
                        default=True,
                        verbose_name="Готовность к удаленной работе",
                    ),
                ),
                (
                    "phone_num",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        blank=True, null=True, verbose_name="О себе"
                    ),
                ),
                (
                    "telegram",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Ссылка на Telegram",
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Ссылка на Linkedin",
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на Github"
                    ),
                ),
                (
                    "stack_overflow",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Ссылка на Stack Overflow",
                    ),
                ),
                (
                    "codeopen",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Ссылка на Codeopen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название"),
                ),
                (
                    "tooltip",
                    models.CharField(max_length=100, verbose_name="Подсказка"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Good", "Хорошее владение"),
                            ("Advanced", "Продвинутое владение"),
                            ("Expect", "Экспертное владение"),
                            ("Pro", "Профессиональное владение"),
                        ],
                        max_length=100,
                        verbose_name="Степень",
                    ),
                ),
                (
                    "percent",
                    models.IntegerField(
                        choices=[
                            (80, "Хорошее владение"),
                            (85, "Продвинутое владение"),
                            (90, "Экспертное владение"),
                            (95, "Профессиональное владение"),
                        ],
                        verbose_name="Процент владения",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="candidate.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recomendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст рекомендации")),
                (
                    "author",
                    models.CharField(
                        max_length=200, verbose_name="Автор рекомендации"
                    ),
                ),
                (
                    "author_job_title",
                    models.CharField(
                        max_length=200,
                        verbose_name="Должность автора рекомендации",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recomendations",
                        to="candidate.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название"),
                ),
                (
                    "level",
                    models.CharField(
                        max_length=200, verbose_name="Уровень владения"
                    ),
                ),
                (
                    "stars",
                    models.CharField(
                        choices=[
                            ("0", "Одна звезда"),
                            ("01", "Две звезды"),
                            ("012", "Три звезды"),
                            ("0123", "Четыре звезды"),
                            ("01234", "Пять звезд"),
                        ],
                        max_length=5,
                        verbose_name="Степень владения",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="candidate.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Должность"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "company",
                    models.CharField(
                        max_length=200, verbose_name="Названи компании"
                    ),
                ),
                (
                    "company_link",
                    models.URLField(verbose_name="Ссылка на сайт компании"),
                ),
                ("date_from", models.DateField(verbose_name="Начало работы")),
                (
                    "date_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Окончание работы"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="candidate.candidate",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_from",),
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название"),
                ),
                (
                    "place",
                    models.CharField(
                        max_length=200, verbose_name="Учебное заведение"
                    ),
                ),
                (
                    "date_from",
                    models.DateField(verbose_name="Начало обучения"),
                ),
                (
                    "date_to",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Окончание обучения",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="candidate.candidate",
                    ),
                ),
            ],
        ),
    ]
