# Generated by Django 4.2 on 2023-04-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст рекомендации')),
                ('author', models.CharField(max_length=200, verbose_name='Автор рекомендации')),
                ('author_job_title', models.CharField(max_length=200, verbose_name='Должность автора рекомендации')),
            ],
        ),
    ]
