# Generated by Django 4.2 on 2023-04-23 10:51

# Third Party Library
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0002_project_otherproject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="previews/",
                verbose_name="Превью",
            ),
        ),
    ]
