# Generated by Django 4.2 on 2023-04-13 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_recomendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recomendations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
