# Generated by Django 4.2 on 2023-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('Good', 'Хорошее владение'), ('Advanced', 'Продвинутое владение'), ('Expert', 'Экспертное владение'), ('Pro', 'Профессиональное владение')], max_length=100, verbose_name='Степень'),
        ),
    ]
