# Generated by Django 4.2 on 2023-07-10 15:49

# Third Party Library
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0005_alter_skill_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="skills_about",
            field=models.TextField(
                blank=True, null=True, verbose_name="О навыках"
            ),
        ),
    ]
