# Generated by Django 4.2 on 2023-07-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_candidate_skills_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='skills_about',
            new_name='about_skills',
        ),
    ]
