# Generated by Django 4.2 on 2023-11-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_rename_skills_about_candidate_about_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate/', verbose_name='Сертификат'),
        ),
    ]
