# Generated by Django 4.2 on 2023-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_alter_education_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_chosen_user',
            field=models.BooleanField(default=True, verbose_name='Выбранный пользователь'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_chosen_user', True)), fields=('is_chosen_user',), name='unique_is_chosen_user'),
        ),
    ]
