# Generated by Django 4.2 on 2023-11-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0010_candidate_is_chosen_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="user",
        ),
        migrations.RemoveField(
            model_name="job",
            name="user",
        ),
        migrations.RemoveField(
            model_name="language",
            name="user",
        ),
        migrations.RemoveField(
            model_name="otherproject",
            name="user",
        ),
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
        migrations.RemoveField(
            model_name="recomendation",
            name="user",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="user",
        ),
        migrations.AddField(
            model_name="candidate",
            name="about_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="О себе"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="about_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="О себе"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="about_skills_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="О навыках"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="about_skills_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="О навыках"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="city_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="city_ru",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="country_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="country_ru",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="name_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="search_job_title_en",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Какую работу ищу",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="search_job_title_ru",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Какую работу ищу",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="surname_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="surname_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="candidate_en",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="candidate_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="date_from_en",
            field=models.DateField(null=True, verbose_name="Начало обучения"),
        ),
        migrations.AddField(
            model_name="education",
            name="date_from_ru",
            field=models.DateField(null=True, verbose_name="Начало обучения"),
        ),
        migrations.AddField(
            model_name="education",
            name="date_to_en",
            field=models.DateField(
                blank=True, null=True, verbose_name="Окончание обучения"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="date_to_ru",
            field=models.DateField(
                blank=True, null=True, verbose_name="Окончание обучения"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="image_en",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="certificate/",
                verbose_name="Сертификат",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="image_ru",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="certificate/",
                verbose_name="Сертификат",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="place_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Учебное заведение"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="place_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Учебное заведение"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="candidate_en",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="candidate_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="company_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Названи компании"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="company_link_en",
            field=models.URLField(
                null=True, verbose_name="Ссылка на сайт компании"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="company_link_ru",
            field=models.URLField(
                null=True, verbose_name="Ссылка на сайт компании"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="company_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Названи компании"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="date_from_en",
            field=models.DateField(null=True, verbose_name="Начало работы"),
        ),
        migrations.AddField(
            model_name="job",
            name="date_from_ru",
            field=models.DateField(null=True, verbose_name="Начало работы"),
        ),
        migrations.AddField(
            model_name="job",
            name="date_to_en",
            field=models.DateField(
                blank=True, null=True, verbose_name="Окончание работы"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="date_to_ru",
            field=models.DateField(
                blank=True, null=True, verbose_name="Окончание работы"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="job",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="job",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Должность"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Должность"
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="languages",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="language",
            name="candidate_en",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="languages",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="candidate_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="languages",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="level_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Уровень владения"
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="level_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Уровень владения"
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="stars_en",
            field=models.CharField(
                choices=[
                    ("0", "Одна звезда"),
                    ("01", "Две звезды"),
                    ("012", "Три звезды"),
                    ("0123", "Четыре звезды"),
                    ("01234", "Пять звезд"),
                ],
                max_length=5,
                null=True,
                verbose_name="Степень владения",
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="stars_ru",
            field=models.CharField(
                choices=[
                    ("0", "Одна звезда"),
                    ("01", "Две звезды"),
                    ("012", "Три звезды"),
                    ("0123", "Четыре звезды"),
                    ("01234", "Пять звезд"),
                ],
                max_length=5,
                null=True,
                verbose_name="Степень владения",
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="otherproject",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_projects",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otherproject",
            name="candidate_en",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_projects",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="otherproject",
            name="candidate_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_projects",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="otherproject",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="otherproject",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="otherproject",
            name="finish_date_en",
            field=models.DateField(
                null=True, verbose_name="Дата завершения проекта"
            ),
        ),
        migrations.AddField(
            model_name="otherproject",
            name="finish_date_ru",
            field=models.DateField(
                null=True, verbose_name="Дата завершения проекта"
            ),
        ),
        migrations.AddField(
            model_name="otherproject",
            name="github_link_en",
            field=models.URLField(null=True, verbose_name="Ссылка на GitHub"),
        ),
        migrations.AddField(
            model_name="otherproject",
            name="github_link_ru",
            field=models.URLField(null=True, verbose_name="Ссылка на GitHub"),
        ),
        migrations.AddField(
            model_name="otherproject",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="otherproject",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="candidate_en",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="candidate_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="project",
            name="finish_date_en",
            field=models.DateField(
                null=True, verbose_name="Дата завершения проекта"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="finish_date_ru",
            field=models.DateField(
                null=True, verbose_name="Дата завершения проекта"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="github_link_en",
            field=models.URLField(null=True, verbose_name="Ссылка на GitHub"),
        ),
        migrations.AddField(
            model_name="project",
            name="github_link_ru",
            field=models.URLField(null=True, verbose_name="Ссылка на GitHub"),
        ),
        migrations.AddField(
            model_name="project",
            name="image_en",
            field=models.ImageField(
                null=True, upload_to="previews/", verbose_name="Превью"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image_ru",
            field=models.ImageField(
                null=True, upload_to="previews/", verbose_name="Превью"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="online_link_en",
            field=models.URLField(null=True, verbose_name="Ссылка на проект"),
        ),
        migrations.AddField(
            model_name="project",
            name="online_link_ru",
            field=models.URLField(null=True, verbose_name="Ссылка на проект"),
        ),
        migrations.AddField(
            model_name="project",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="recomendation",
            name="author_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Автор рекомендации"
            ),
        ),
        migrations.AddField(
            model_name="recomendation",
            name="author_job_title_en",
            field=models.CharField(
                max_length=200,
                null=True,
                verbose_name="Должность автора рекомендации",
            ),
        ),
        migrations.AddField(
            model_name="recomendation",
            name="author_job_title_ru",
            field=models.CharField(
                max_length=200,
                null=True,
                verbose_name="Должность автора рекомендации",
            ),
        ),
        migrations.AddField(
            model_name="recomendation",
            name="author_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Автор рекомендации"
            ),
        ),
        migrations.AddField(
            model_name="recomendation",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recomendations",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recomendation",
            name="candidate_en",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recomendations",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="recomendation",
            name="candidate_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recomendations",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="recomendation",
            name="text_en",
            field=models.TextField(
                null=True, verbose_name="Текст рекомендации"
            ),
        ),
        migrations.AddField(
            model_name="recomendation",
            name="text_ru",
            field=models.TextField(
                null=True, verbose_name="Текст рекомендации"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="candidate_en",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="candidate_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="candidate.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="level_en",
            field=models.CharField(
                choices=[
                    ("Good", "Хорошее владение"),
                    ("Advanced", "Продвинутое владение"),
                    ("Expert", "Экспертное владение"),
                    ("Pro", "Профессиональное владение"),
                ],
                max_length=100,
                null=True,
                verbose_name="Степень",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="level_ru",
            field=models.CharField(
                choices=[
                    ("Good", "Хорошее владение"),
                    ("Advanced", "Продвинутое владение"),
                    ("Expert", "Экспертное владение"),
                    ("Pro", "Профессиональное владение"),
                ],
                max_length=100,
                null=True,
                verbose_name="Степень",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="percent_en",
            field=models.IntegerField(
                choices=[
                    (80, "Хорошее владение"),
                    (85, "Продвинутое владение"),
                    (90, "Экспертное владение"),
                    (95, "Профессиональное владение"),
                ],
                null=True,
                verbose_name="Процент владения",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="percent_ru",
            field=models.IntegerField(
                choices=[
                    (80, "Хорошее владение"),
                    (85, "Продвинутое владение"),
                    (90, "Экспертное владение"),
                    (95, "Профессиональное владение"),
                ],
                null=True,
                verbose_name="Процент владения",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="tooltip_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Подсказка"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="tooltip_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Подсказка"
            ),
        ),
    ]
