# Generated by Django 4.2 on 2023-11-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0012_remove_education_candidate_en_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="candidate",
            name="unique_is_chosen_user",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="is_chosen_user",
        ),
        migrations.AddField(
            model_name="candidate",
            name="is_chosen_candidate",
            field=models.BooleanField(
                default=True, verbose_name="Chosen candidate"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about",
            field=models.TextField(
                blank=True, null=True, verbose_name="About candidate"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="About candidate"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="About candidate"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_skills",
            field=models.TextField(
                blank=True, null=True, verbose_name="About candidate's skills"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_skills_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="About candidate's skills"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_skills_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="About candidate's skills"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="city",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="city_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="city_ru",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="codeopen",
            field=models.URLField(
                blank=True, null=True, verbose_name="Codeopen link"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="country",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="country_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="country_ru",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="distant_work",
            field=models.BooleanField(
                default=True, verbose_name="Ready for remote job"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="github",
            field=models.URLField(
                blank=True, null=True, verbose_name="Github link"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_image/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="linkedin",
            field=models.URLField(
                blank=True, null=True, verbose_name="Linkedin link"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="name_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone_num",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="search_job_title",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="What job the candidate wants to find",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="search_job_title_en",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="What job the candidate wants to find",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="search_job_title_ru",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="What job the candidate wants to find",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="stack_overflow",
            field=models.URLField(
                blank=True, null=True, verbose_name="Stack Overflow link"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="surname",
            field=models.CharField(max_length=200, verbose_name="Surname"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="surname_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Surname"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="surname_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Surname"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="telegram",
            field=models.URLField(
                blank=True, null=True, verbose_name="Telegram link"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="candidate.candidate",
                verbose_name="Candidate",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="date_from",
            field=models.DateField(verbose_name="Date from"),
        ),
        migrations.AlterField(
            model_name="education",
            name="date_to",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date to"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="certificate/",
                verbose_name="Certificate",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="place",
            field=models.CharField(
                max_length=200, verbose_name="Institution name"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="place_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Institution name"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="place_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Institution name"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="education",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="candidate.candidate",
                verbose_name="Candidate",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.CharField(
                max_length=200, verbose_name="Company name"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="company_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Company name"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="company_link",
            field=models.URLField(verbose_name="Company's website url"),
        ),
        migrations.AlterField(
            model_name="job",
            name="company_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Company name"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="date_from",
            field=models.DateField(verbose_name="Date from"),
        ),
        migrations.AlterField(
            model_name="job",
            name="date_to",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date to"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="job",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="job",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="job",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="languages",
                to="candidate.candidate",
                verbose_name="Candidate",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="level",
            field=models.CharField(max_length=200, verbose_name="Level"),
        ),
        migrations.AlterField(
            model_name="language",
            name="level_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Level"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="level_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Level"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="stars",
            field=models.CharField(
                choices=[
                    ("0", "One star"),
                    ("01", "Two stars"),
                    ("012", "Three stars"),
                    ("0123", "Four stars"),
                    ("01234", "Five stars"),
                ],
                max_length=5,
                verbose_name="Extent",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="language",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="otherproject",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_projects",
                to="candidate.candidate",
                verbose_name="Candidate",
            ),
        ),
        migrations.AlterField(
            model_name="otherproject",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="otherproject",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="otherproject",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="otherproject",
            name="finish_date",
            field=models.DateField(verbose_name="Project end date"),
        ),
        migrations.AlterField(
            model_name="otherproject",
            name="github_link",
            field=models.URLField(verbose_name="Github link"),
        ),
        migrations.AlterField(
            model_name="otherproject",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="otherproject",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="otherproject",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="candidate.candidate",
                verbose_name="Candidate",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="finish_date",
            field=models.DateField(verbose_name="Project end date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_link",
            field=models.URLField(verbose_name="Github link"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                upload_to="previews/", verbose_name="Preview"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="online_link",
            field=models.URLField(verbose_name="Link"),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="author",
            field=models.CharField(max_length=200, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="author_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Author"
            ),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="author_job_title",
            field=models.CharField(
                max_length=200, verbose_name="Author's job title"
            ),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="author_job_title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Author's job title"
            ),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="author_job_title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Author's job title"
            ),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="author_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Author"
            ),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recomendations",
                to="candidate.candidate",
                verbose_name="Candidate",
            ),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="text",
            field=models.TextField(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="text_en",
            field=models.TextField(null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="text_ru",
            field=models.TextField(null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="candidate.candidate",
                verbose_name="Candidate",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.CharField(
                choices=[
                    ("Good", "Good"),
                    ("Advanced", "Advanced"),
                    ("Expert", "Expert"),
                    ("Pro", "Pro"),
                ],
                max_length=100,
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="percent",
            field=models.IntegerField(
                choices=[
                    (80, "Good"),
                    (85, "Advanced"),
                    (90, "Expert"),
                    (95, "Pro"),
                ],
                verbose_name="Percentage",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="tooltip",
            field=models.CharField(max_length=100, verbose_name="Tooltip"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="tooltip_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Tooltip"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="tooltip_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Tooltip"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_chosen_candidate", True)),
                fields=("is_chosen_candidate",),
                name="unique_is_chosen_candidate",
            ),
        ),
    ]
