# Generated by Django 4.2 on 2023-11-24 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0013_remove_candidate_unique_is_chosen_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="tooltip",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="tooltip_en",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="tooltip_ru",
        ),
    ]
