# Generated by Django 4.2 on 2023-11-27 18:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_rename_skill_hardskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskill',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hard_skills', to='candidate.candidate', verbose_name='Candidate'),
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('level', models.CharField(choices=[('Good', 'Good'), ('Advanced', 'Advanced'), ('Expert', 'Expert'), ('Pro', 'Pro')], max_length=100, verbose_name='Level')),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Percentage')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_skills', to='candidate.candidate', verbose_name='Candidate')),
            ],
            options={
                'ordering': ('-percent',),
                'abstract': False,
            },
        ),
    ]
