# Generated by Django 4.2 on 2023-11-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_softskill_tooltip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softskill',
            name='level',
        ),
        migrations.RemoveField(
            model_name='softskill',
            name='tooltip',
        ),
    ]
