# Generated by Django 4.2 on 2023-11-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0021_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
