# Generated by Django 4.2 on 2023-11-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0023_remove_file_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='candidate',
        ),
        migrations.AddField(
            model_name='job',
            name='candidate',
            field=models.ManyToManyField(related_name='jobs', to='candidate.candidate', verbose_name='Candidate'),
        ),
    ]
