# Generated by Django 4.2 on 2023-11-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0024_remove_job_candidate_job_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='hardskill',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='language',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='otherproject',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='recomendation',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='softskill',
            name='candidate',
        ),
        migrations.AddField(
            model_name='education',
            name='candidate',
            field=models.ManyToManyField(related_name='educations', to='candidate.candidate', verbose_name='Candidate'),
        ),
        migrations.AddField(
            model_name='hardskill',
            name='candidate',
            field=models.ManyToManyField(related_name='hard_skills', to='candidate.candidate', verbose_name='Candidate'),
        ),
        migrations.AddField(
            model_name='language',
            name='candidate',
            field=models.ManyToManyField(related_name='languages', to='candidate.candidate', verbose_name='Candidate'),
        ),
        migrations.AddField(
            model_name='otherproject',
            name='candidate',
            field=models.ManyToManyField(related_name='other_projects', to='candidate.candidate', verbose_name='Candidate'),
        ),
        migrations.AddField(
            model_name='project',
            name='candidate',
            field=models.ManyToManyField(related_name='projects', to='candidate.candidate', verbose_name='Candidate'),
        ),
        migrations.AddField(
            model_name='recomendation',
            name='candidate',
            field=models.ManyToManyField(related_name='recomendations', to='candidate.candidate', verbose_name='Candidate'),
        ),
        migrations.AddField(
            model_name='softskill',
            name='candidate',
            field=models.ManyToManyField(related_name='soft_skills', to='candidate.candidate', verbose_name='Candidate'),
        ),
    ]
