# Generated by Django 4.2 on 2023-12-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0026_candidate_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=30, verbose_name="Tag")),
                (
                    "tag_ru",
                    models.CharField(
                        max_length=30, null=True, verbose_name="Tag"
                    ),
                ),
                (
                    "tag_en",
                    models.CharField(
                        max_length=30, null=True, verbose_name="Tag"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="achievements",
            field=models.TextField(
                blank=True,
                help_text="Each achievement with new line",
                null=True,
                verbose_name="Achievements",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                related_name="projects",
                to="candidate.tag",
                verbose_name="Tags",
            ),
        ),
    ]
