# Generated by Django 4.2 on 2023-12-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0027_tag_project_achievements_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Tag"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_en",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="Tag"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_ru",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="Tag"
            ),
        ),
    ]
