# Generated by Django 4.2 on 2023-12-08 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0028_alter_tag_tag_alter_tag_tag_en_alter_tag_tag_ru"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="tag",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="tag_en",
            new_name="title_en",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="tag_ru",
            new_name="title_ru",
        ),
    ]
