# Generated by Django 4.2 on 2023-12-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "candidate",
            "0029_rename_tag_tag_title_rename_tag_en_tag_title_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title_en",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title_ru",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="Title"
            ),
        ),
    ]
