# Generated by Django 4.2 on 2023-12-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0030_alter_tag_title_alter_tag_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="achievements_en",
            field=models.TextField(
                blank=True,
                help_text="Each achievement with a new line",
                null=True,
                verbose_name="Achievements",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="achievements_ru",
            field=models.TextField(
                blank=True,
                help_text="Each achievement with a new line",
                null=True,
                verbose_name="Achievements",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="achievements",
            field=models.TextField(
                blank=True,
                help_text="Each achievement with a new line",
                null=True,
                verbose_name="Achievements",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                help_text="[key goal], [what you've implemented in the project]",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_en",
            field=models.TextField(
                help_text="[key goal], [what you've implemented in the project]",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_ru",
            field=models.TextField(
                help_text="[key goal], [what you've implemented in the project]",
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
