# Generated by Django 4.2 on 2023-12-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "candidate",
            "0031_project_achievements_en_project_achievements_ru_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                help_text="General description in one sentence, key goal, what you've implemented in the project. 3-4 santances",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_en",
            field=models.TextField(
                help_text="General description in one sentence, key goal, what you've implemented in the project. 3-4 santances",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_ru",
            field=models.TextField(
                help_text="General description in one sentence, key goal, what you've implemented in the project. 3-4 santances",
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
