# Generated by Django 4.2 on 2023-12-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0032_alter_project_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tag",
            new_name="Stack",
        ),
        migrations.RemoveField(
            model_name="project",
            name="tags",
        ),
        migrations.AddField(
            model_name="project",
            name="stack",
            field=models.ManyToManyField(
                related_name="projects",
                to="candidate.stack",
                verbose_name="Stack",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="achievements",
            field=models.TextField(
                blank=True,
                help_text="Each achievement with a new line. Ex.: ",
                null=True,
                verbose_name="Achievements",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="achievements_en",
            field=models.TextField(
                blank=True,
                help_text="Each achievement with a new line. Ex.: ",
                null=True,
                verbose_name="Achievements",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="achievements_ru",
            field=models.TextField(
                blank=True,
                help_text="Each achievement with a new line. Ex.: ",
                null=True,
                verbose_name="Achievements",
            ),
        ),
    ]
