# Generated by Django 4.2 on 2023-12-08 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0034_remove_project_achievements_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="achievements",
        ),
    ]
