# Generated by Django 4.2 on 2024-01-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0035_remove_project_achievements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': [models.OrderBy(models.F('date_to'), descending=True, nulls_first=True), '-date_from']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_search_status',
            field=models.CharField(choices=[('Active', 'In active search'), ('Passive', 'Open for job offers'), ('Inactive', 'Not looking for a job')], default='Active', max_length=100, verbose_name='Job search status'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ready_to_relocate',
            field=models.BooleanField(default=False, verbose_name='Ready to relocate'),
        ),
    ]
