# Generated by Django 4.2 on 2024-01-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0036_alter_job_options_candidate_job_search_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('view_date', models.DateTimeField(auto_now_add=True, verbose_name='View date')),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_search_status',
            field=models.CharField(choices=[('Active', 'In active search'), ('Passive', 'Open to opportunities'), ('Inactive', 'Not looking for a job')], default='Active', max_length=100, verbose_name='Job search status'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='candidate', to='candidate.ip'),
        ),
    ]
