# Generated by Django 4.2 on 2024-01-26 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0038_remove_candidate_views_ip_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='view_date',
        ),
        migrations.AddField(
            model_name='ip',
            name='view_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='View datetime'),
            preserve_default=False,
        ),
    ]
