# Generated by Django 4.2 on 2023-04-13 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='previews/', verbose_name='Превью')),
                ('online_link', models.URLField(verbose_name='Ссылка на проект')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('github_link', models.URLField(verbose_name='Ссылка на GitHub')),
                ('finish_date', models.DateField(verbose_name='Дата завершения проекта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-finish_date',),
            },
        ),
        migrations.CreateModel(
            name='OtherProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('github_link', models.URLField(verbose_name='Ссылка на GitHub')),
                ('finish_date', models.DateField(verbose_name='Дата завершения проекта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-finish_date',),
            },
        ),
    ]
